# This file is used for local environment

version: "3"
services:

  backend:
    image: pulseapi:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8001:8001
    environment:
      - APP_ENV=dev
      - APP_BASE_URL=0.0.0.0
      - PORT=8001
      - DATABASE_URL=postgres://webmaster:EventN0tifY@db/pulse

  db:
    image: docker.io/postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      # Use `:Z` in SELinux-enabled disro.
      - ./cdata/db:/var/lib/postgresql/data/:Z
    environment:
      POSTGRES_USER: webmaster
      POSTGRES_PASSWORD: EventN0tifY
      POSTGRES_DB: pulse
